# metal:
#   children:
#     masters:
#       hosts:
#         homelab0: {ansible_host: 192.168.1.110, mac: '0a:04:7a:cb:37:07', disk: sda, network_interface: en0}
#         homelab1: {ansible_host: 192.168.1.111, mac: '1e:69:f7:10:26:3c', disk: sda, network_interface: en0}
#     workers:
#       hosts:
#         homelab2: {ansible_host: 192.168.1.113, mac: '5e:5a:2b:06:96:ba', disk: sda, network_interface: en0}

metal:
  children:
    masters:
      hosts:
        homelab0: {ansible_host: 192.168.1.114, mac: 'b2:98:ce:6e:83:4a', disk: vda, network_interface: en0}
        homelab1: {ansible_host: 192.168.1.115, mac: 'd2:da:68:97:8d:3a', disk: vda, network_interface: en0}
    workers:
      hosts:
        homelab2: {ansible_host: 192.168.1.116, mac: 'c6:8b:92:af:a5:92', disk: vda, network_interface: en0}
