metal:
  children:
    masters:
      hosts:
        homelab0: {ansible_host: 192.168.1.110, mac: '0A:04:7A:CB:37:07', disk: blk0, network_interface: en0}
        homelab1: {ansible_host: 192.168.1.111, mac: '1E:69:F7:10:26:3C', disk: blk0, network_interface: en0}
    workers:
      hosts:
        homelab2: {ansible_host: 192.168.1.113, mac: '5E:5A:2B:06:96:BA', disk: blk0, network_interface: en0}
